#ValueError
"""
     thrown when a function's argument is of an inappropriate type.
"""

    
print(int(10))

